name: tests

on:
  push:
    branches:
      - "master"
      - "devel"

env:
  cache-version: 'cache-v1'

jobs:
  tests:    
    timeout-minutes: 720
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 5
      matrix:
        config:
          - { python-version: 3.7, os: ubuntu-latest }
          - { python-version: 3.8, os: ubuntu-latest }
          - { python-version: 3.9, os: ubuntu-latest }
          # I think there's dependencies issues that's messing up this
          # 3.8 fails on macosx likely because of issue noted here:
          # https://github.com/scipy/scipy/issues/11835
          - { python-version: 3.7, os: macos-latest }
          - { python-version: 3.8, os: macos-latest }
          - { python-version: 3.9, os: macos-latest }
    runs-on: ${{ matrix.config.os }}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      NOT_CRAN: true
      TZ: UTC
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install system dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev
        sysreqs=$(Rscript -e 'cat("apt-get update -y && apt-get install -y", paste(gsub("apt-get install -y ", "", remotes::system_requirements("ubuntu", "20.04")), collapse = " "))')
        echo $sysreqs
        sudo -s eval "$sysreqs"
        
    - name: Cache conda
      uses: actions/cache@v1
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('environment.yml') }}
            
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        auto-activate-base: true
        auto-update-conda : true
        activate-environment: dandelion
        channels: conda-forge, bioconda, anaconda, defaults
        channel-priority: true
        python-version: ${{ matrix.config.python-version }}
        environment-file: environment.yml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

    - name: Test with pytest
      run: |
        pytest -rP tests -W ignore::DeprecationWarning -W ignore::PendingDeprecationWarning -W ignore::FutureWarning
