name: Test Singularity Build
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code for the container build
        uses: actions/checkout@v3
      - name: Singularity install with defaults
        uses: singularityhub/install-singularity@main
      - name: Build Container
        run: |
          cat environment.yml
          sudo -E singularity build test.sif test.def
